---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: humioscheduledsearches.core.humio.com
  labels:
    app: 'humio-operator'
    app.kubernetes.io/name: 'humio-operator'
    app.kubernetes.io/instance: 'humio-operator'
    app.kubernetes.io/managed-by: 'Helm'
    helm.sh/chart: 'humio-operator-0.27.2'
spec:
  group: core.humio.com
  names:
    kind: HumioScheduledSearch
    listKind: HumioScheduledSearchList
    plural: humioscheduledsearches
    singular: humioscheduledsearch
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HumioScheduledSearch is the Schema for the HumioScheduledSearches
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HumioScheduledSearchSpec defines the desired state of HumioScheduledSearch
            properties:
              actions:
                description: Actions is the list of Humio Actions by name that will
                  be triggered by this scheduled search
                items:
                  type: string
                type: array
              backfillLimit:
                description: BackfillLimit is the user-defined limit, which caps the
                  number of missed searches to backfill, e.g. in the event of a shutdown.
                type: integer
              description:
                description: Description is the description of the scheduled search
                type: string
              enabled:
                default: false
                description: Enabled will set the ScheduledSearch to enabled when
                  set to true
                type: boolean
              externalClusterName:
                description: |-
                  ExternalClusterName refers to an object of type HumioExternalCluster where the Humio resources should be created.
                  This conflicts with ManagedClusterName.
                type: string
              labels:
                description: Labels are a set of labels on the scheduled search
                items:
                  type: string
                type: array
              managedClusterName:
                description: |-
                  ManagedClusterName refers to an object of type HumioCluster that is managed by the operator where the Humio
                  resources should be created.
                  This conflicts with ExternalClusterName.
                type: string
              name:
                description: Name is the name of the scheduled search inside Humio
                minLength: 1
                type: string
              queryEnd:
                description: QueryEnd is the end of the relative time interval for
                  the query.
                type: string
              queryStart:
                description: QueryStart is the start of the relative time interval
                  for the query.
                type: string
              queryString:
                description: QueryString defines the desired Humio query string
                type: string
              schedule:
                description: Schedule is the cron pattern describing the schedule
                  to execute the query on.
                type: string
              timeZone:
                description: TimeZone is the time zone of the schedule. Currently,
                  this field only supports UTC offsets like 'UTC', 'UTC-01' or 'UTC+12:45'.
                type: string
              viewName:
                description: ViewName is the name of the Humio View under which the
                  scheduled search will be managed. This can also be a Repository
                minLength: 1
                type: string
            required:
            - actions
            - backfillLimit
            - name
            - queryEnd
            - queryStart
            - queryString
            - schedule
            - timeZone
            - viewName
            type: object
          status:
            description: HumioScheduledSearchStatus defines the observed state of
              HumioScheduledSearch
            properties:
              state:
                description: State reflects the current state of the HumioScheduledSearch
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
