kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          v: "10"
  - role: worker
    labels:
      "topology.kubernetes.io/zone": "us-west-2a"
  - role: worker
    labels:
      "topology.kubernetes.io/zone": "us-west-2b"
  - role: worker
    labels:
      "topology.kubernetes.io/zone": "us-west-2c"
