apiVersion: v1
name: humio-operator
version: 0.28.3
appVersion: 0.28.3
home: https://github.com/humio/humio-operator
description: |
  Kubernetes Operator for running Humio on top of Kubernetes
  Upgrade notes can be found at https://library.humio.com/falcon-logscale-self-hosted/installation-kubernetes-operator-upgrade.html#installation-containers-kubernetes-operator-upgrade-notes
icon: https://www.humio.com/static/3ae40396981ac553b27d76dabefe0caa/9911c/logo--og-humio.png
sources:
- https://github.com/humio/humio-operator
maintainers:
- name: SaaldjorMike
- name: jswoods
- name: schofield

