## Append samples of your project ##
resources:
- core_v1alpha1_humioaction.yaml
- core_v1alpha1_humioaggregatealert.yaml
- core_v1alpha1_humioalert.yaml
- core_v1alpha1_humiobootstraptoken.yaml
- core_v1alpha1_humiocluster.yaml
- core_v1alpha1_humiocluster-affinity-and-tolerations.yaml
- core_v1alpha1_humiocluster-data-volume-persistent-volume-claim-policy-kind-local.yaml
- core_v1alpha1_humiocluster-ephemeral-with-gcs-storage.yaml
- core_v1alpha1_humiocluster-ephemeral-with-s3-storage.yaml
- core_v1alpha1_humiocluster-kind-local.yaml
- core_v1alpha1_humiocluster-multi-nodepool-kind-local.yaml
- core_v1alpha1_humiocluster-nginx-ingress-with-cert-manager.yaml
- core_v1alpha1_humiocluster-nginx-ingress-with-custom-path.yaml
- core_v1alpha1_humiocluster-nginx-ingress-with-hostname-secrets.yaml
- core_v1alpha1_humiocluster-nodepool-slice-only.yaml
- core_v1alpha1_humiocluster-persistent-volumes.yaml
- core_v1alpha1_humioexternalcluster.yaml
- core_v1alpha1_humiofeatureflag.yaml
- core_v1alpha1_humiofilteralert.yaml
- core_v1alpha1_humioingesttoken.yaml
- core_v1alpha1_humioparser.yaml
- core_v1alpha1_humiorepository.yaml
- core_v1alpha1_humioscheduledsearch.yaml
- core_v1alpha1_humioview.yaml
- core_v1alpha1_humiouser.yaml
- core_v1alpha1_humiopdfrenderservice.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
