---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.0
  name: humioexternalclusters.core.humio.com
  labels:
    app: 'humio-operator'
    app.kubernetes.io/name: 'humio-operator'
    app.kubernetes.io/instance: 'humio-operator'
    app.kubernetes.io/managed-by: 'Helm'
    helm.sh/chart: 'humio-operator-0.29.0'
spec:
  group: core.humio.com
  names:
    kind: HumioExternalCluster
    listKind: HumioExternalClusterList
    plural: humioexternalclusters
    singular: humioexternalcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The state of the external Humio cluster
      jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HumioExternalCluster is the Schema for the humioexternalclusters
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HumioExternalClusterSpec defines the desired state of HumioExternalCluster.
            properties:
              apiTokenSecretName:
                description: |-
                  APITokenSecretName is used to obtain the API token we need to use when communicating with the external Humio cluster.
                  It refers to a Kubernetes secret that must be located in the same namespace as the HumioExternalCluster.
                  The humio-operator instance must be able to read the content of the Kubernetes secret.
                  The Kubernetes secret must be of type opaque, and contain the key "token" which holds the Humio API token.
                  Depending on the use-case it is possible to use different token types, depending on what resources it will be
                  used to manage, e.g. HumioParser.
                  In most cases, it is recommended to create a dedicated user within the LogScale cluster and grant the
                  appropriate permissions to it, then use the personal API token for that user.
                type: string
              caSecretName:
                description: |-
                  CASecretName is used to point to a Kubernetes secret that holds the CA that will be used to issue intra-cluster TLS certificates.
                  The secret must contain a key "ca.crt" which holds the CA certificate in PEM format.
                type: string
              insecure:
                description: Insecure is used to disable TLS certificate verification
                  when communicating with Humio clusters over TLS.
                type: boolean
              url:
                description: Url is used to connect to the Humio cluster we want to
                  use.
                minLength: 1
                type: string
            required:
            - url
            type: object
          status:
            description: HumioExternalClusterStatus defines the observed state of
              HumioExternalCluster.
            properties:
              state:
                description: State reflects the current state of the HumioExternalCluster
                type: string
              version:
                description: Version shows the Humio cluster version of the HumioExternalCluster
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
