---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: humioactions.core.humio.com
spec:
  group: core.humio.com
  names:
    kind: HumioAction
    listKind: HumioActionList
    plural: humioactions
    singular: humioaction
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HumioAction is the Schema for the humioactions API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HumioActionSpec defines the desired state of HumioAction.
            properties:
              emailProperties:
                description: EmailProperties indicates this is an Email Action, and
                  contains the corresponding properties
                properties:
                  bodyTemplate:
                    description: BodyTemplate holds the email body template
                    type: string
                  recipients:
                    description: Recipients holds the list of email addresses that
                      the action should send emails to.
                    items:
                      type: string
                    minItems: 1
                    type: array
                  subjectTemplate:
                    description: SubjectTemplate holds the email subject template
                    type: string
                  useProxy:
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
              externalClusterName:
                description: |-
                  ExternalClusterName refers to an object of type HumioExternalCluster where the Humio resources should be created.
                  This conflicts with ManagedClusterName.
                type: string
              humioRepositoryProperties:
                description: HumioRepositoryProperties indicates this is a Humio Repository
                  Action, and contains the corresponding properties
                properties:
                  ingestToken:
                    description: |-
                      IngestToken specifies what ingest token to use.
                      If both IngestToken and IngestTokenSource are specified, IngestToken will be used.
                    type: string
                  ingestTokenSource:
                    description: |-
                      IngestTokenSource specifies where to fetch the ingest token from.
                      If both IngestToken and IngestTokenSource are specified, IngestToken will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                type: object
              managedClusterName:
                description: |-
                  ManagedClusterName refers to an object of type HumioCluster that is managed by the operator where the Humio
                  resources should be created.
                  This conflicts with ExternalClusterName.
                type: string
              name:
                description: Name is the name of the Action
                minLength: 1
                type: string
              opsGenieProperties:
                description: OpsGenieProperties indicates this is a Ops Genie Action,
                  and contains the corresponding properties
                properties:
                  apiUrl:
                    description: ApiUrl holds the API URL the action should use when
                      calling OpsGenie
                    type: string
                  genieKey:
                    description: |-
                      GenieKey specifies what API key to use.
                      If both GenieKey and GenieKeySource are specified, GenieKey will be used.
                    type: string
                  genieKeySource:
                    description: |-
                      GenieKeySource specifies where to fetch the API key from.
                      If both GenieKey and GenieKeySource are specified, GenieKey will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  useProxy:
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
              pagerDutyProperties:
                description: PagerDutyProperties indicates this is a PagerDuty Action,
                  and contains the corresponding properties
                properties:
                  routingKey:
                    description: |-
                      RoutingKey specifies what API key to use.
                      If both RoutingKey and RoutingKeySource are specified, RoutingKey will be used.
                    type: string
                  routingKeySource:
                    description: |-
                      RoutingKeySource specifies where to fetch the routing key from.
                      If both RoutingKey and RoutingKeySource are specified, RoutingKey will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  severity:
                    description: Severity defines which severity is used in the request
                      to PagerDuty
                    type: string
                  useProxy:
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
              slackPostMessageProperties:
                description: SlackPostMessageProperties indicates this is a Slack
                  Post Message Action, and contains the corresponding properties
                properties:
                  apiToken:
                    description: |-
                      ApiToken specifies what API key to use.
                      If both ApiToken and ApiTokenSource are specified, ApiToken will be used.
                    type: string
                  apiTokenSource:
                    description: |-
                      ApiTokenSource specifies where to fetch the API key from.
                      If both ApiToken and ApiTokenSource are specified, ApiToken will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  channels:
                    description: Channels holds the list of Slack channels that the
                      action should post to.
                    items:
                      type: string
                    type: array
                  fields:
                    additionalProperties:
                      type: string
                    default: {}
                    description: Fields holds a key-value map of additional fields
                      to attach to the payload sent to Slack.
                    type: object
                  useProxy:
                    default: false
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
              slackProperties:
                description: SlackProperties indicates this is a Slack Action, and
                  contains the corresponding properties
                properties:
                  fields:
                    additionalProperties:
                      type: string
                    description: Fields holds a key-value map of additional fields
                      to attach to the payload sent to Slack.
                    type: object
                  url:
                    description: |-
                      Url specifies what URL to use.
                      If both Url and UrlSource are specified, Url will be used.
                    type: string
                  urlSource:
                    description: |-
                      UrlSource specifies where to fetch the URL from.
                      If both Url and UrlSource are specified, Url will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  useProxy:
                    default: false
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
              victorOpsProperties:
                description: VictorOpsProperties indicates this is a VictorOps Action,
                  and contains the corresponding properties
                properties:
                  messageType:
                    description: MessageType contains the VictorOps message type to
                      use when the action calls VictorOps
                    type: string
                  notifyUrl:
                    description: |-
                      NotifyUrl specifies what URL to use.
                      If both NotifyUrl and NotifyUrlSource are specified, NotifyUrl will be used.
                    type: string
                  notifyUrlSource:
                    description: |-
                      NotifyUrlSource specifies where to fetch the URL from.
                      If both NotifyUrl and NotifyUrlSource are specified, NotifyUrl will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  useProxy:
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                required:
                - notifyUrlSource
                type: object
              viewName:
                description: ViewName is the name of the Humio View under which the
                  Action will be managed. This can also be a Repository
                minLength: 1
                type: string
              webhookProperties:
                description: WebhookProperties indicates this is a Webhook Action,
                  and contains the corresponding properties
                properties:
                  bodyTemplate:
                    description: BodyTemplate holds the webhook body template
                    type: string
                  headers:
                    additionalProperties:
                      type: string
                    description: |-
                      Headers specifies what HTTP headers to use.
                      If both Headers and SecretHeaders are specified, they will be merged together.
                    type: object
                  ignoreSSL:
                    description: IgnoreSSL configures the action so that skips TLS
                      certificate verification
                    type: boolean
                  method:
                    description: Method holds the HTTP method that the action will
                      use
                    type: string
                  secretHeaders:
                    default: []
                    description: |-
                      SecretHeaders specifies what HTTP headers to use and where to fetch the values from.
                      If both Headers and SecretHeaders are specified, they will be merged together.
                    items:
                      description: HeadersSource defines a header and corresponding
                        source for the value of it.
                      properties:
                        name:
                          description: Name is the name of the header.
                          minLength: 1
                          type: string
                        valueFrom:
                          description: ValueFrom defines where to fetch the value
                            of the header from.
                          properties:
                            secretKeyRef:
                              $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                              description: SecretKeyRef allows specifying which secret
                                and what key in that secret holds the value we want
                                to use
                          type: object
                      required:
                      - name
                      type: object
                    type: array
                  url:
                    description: |-
                      Url specifies what URL to use
                      If both Url and UrlSource are specified, Url will be used.
                    type: string
                  urlSource:
                    description: |-
                      UrlSource specifies where to fetch the URL from
                      If both Url and UrlSource are specified, Url will be used.
                    properties:
                      secretKeyRef:
                        $ref: '#/definitions/k8s.io~1api~1core~1v1~0SecretKeySelector'
                        description: SecretKeyRef allows specifying which secret and
                          what key in that secret holds the value we want to use
                    type: object
                  useProxy:
                    description: |-
                      UseProxy is used to configure if the action should use the proxy configured on the system. For more details,
                      see https://library.humio.com/falcon-logscale-self-hosted/configuration-http-proxy.html
                    type: boolean
                type: object
            required:
            - name
            - viewName
            type: object
          status:
            description: HumioActionStatus defines the observed state of HumioAction.
            properties:
              state:
                description: State reflects the current state of the HumioAction
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
